version: '3'
services:
  graph-node:
    environment:
      ethereum: 'test:http://chain:2000'
  chain:
    image: snap-testchain
    build:
      context: ../lib/geb-snap-testchain
    container_name: testchain
    ports:
      - '8545:8545'
      - '8546:8546'
    expose:
      - '8545'
      - '8546'
    environment:
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_PASSWORD=${GIT_PASSWORD}
    command: >
      ./home/reflexer/.nix-profile/etc/profile.d/nix.sh
      && nix run -v -f /home/reflexer/lib/geb-deployment-scripts -c ./scripts/launch
